// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/renfy96/yy-layout-v1/internal/repository"
	"github.com/renfy96/yy-layout-v1/internal/router"
	"github.com/renfy96/yy-layout-v1/pkg/log"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	_ = repository.NewDb(viperViper)
	engine := router.NewServerHTTP(logger)
	return engine, func() {
	}, nil
}

// wire.go:

// RepositorySet 仓储

var ServerSet = wire.NewSet(router.NewServerHTTP)
